version: '1.0'
name: pipeline-20221007
displayName: pipeline-20221007
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-4540ad0f
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - bash getFrontendLog.sh
          - bash getBackendLog.sh
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./docs/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-bf602405
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: qiwen
          hostID:
            - 8c013cf3-ba18-43f1-9dc7-bbee3d84b70c
        deployArtifact:
          - source: build
            name: qiwen-file-doc
            target: ~/gitee_go/deploy/qiwen-file-doc
            dependArtifact: BUILD_ARTIFACT
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - '# mkdir -p /home/admin/app'
          - '# tar zxvf ~/gitee_go/deploy/output.tar.gz -C /home/admin/app'
          - '# sh /home/admin/app/deploy.sh restart'
          - '# 如果你是php之类的无需制品包的制品方式，可以使用 git clone 或者 git pull 将源代码更新到服务器，再执行其他命令'
          - '# git clone ***@***.git'
          - ''
          - cd ~/gitee_go/deploy/qiwen-file-doc
          - tar -zxvf qiwen-file-doc.tar.gz
          - ''
          - rm -r /home/html/qiwen-file-doc
          - cp -r dist /home/html/qiwen-file-doc
          - ''
          - ''
          - ' echo ''Hello Gitee!'''
        notify: []
        strategy:
          retry: '0'
